apiVersion: 1

datasources:
  - name: Oppi Telemetry SQLite
    uid: oppi-telemetry-sqlite
    type: frser-sqlite-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/oppi-telemetry/telemetry.db
      pathPrefix: "file:"
      pathOptions: mode=ro
      attachLimit: 0
